api_platform:
    version: 0.1.4
    title: Hello API Platform
    serializer:
        hydra_prefix: true
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        multipart:
            mime_types: ['multipart/form-data']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin', 'X-LOCALE', 'Accept-Language']
    oauth:
        enabled: true
        clientId: '%env(OAUTH_KEYCLOAK_CLIENT_ID_SWAGGER)%'
        type: 'oauth2'
        flow: 'authorizationCode'
        authorizationUrl: '%env(OAUTH_KEYCLOAK_ISSUER)%/realms/%env(OAUTH_KEYCLOAK_REALM)%/protocol/openid-connect/auth'
        tokenUrl: '%env(OAUTH_KEYCLOAK_ISSUER)%/realms/%env(OAUTH_KEYCLOAK_REALM)%/protocol/openid-connect/token'