api_platform:
    version: 0.0.0
    title: Hello API Platform
    serializer:
        hydra_prefix: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin', 'X-LOCALE', 'Accept-Language']
