security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        keycloak_bearer_user_provider:
            id: FilmAnalogger\FilmAnaloggerApi\Security\KeycloakBearerUserProvider


    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        apiPlatform:
            pattern: ^/$
            security: false

        redoc:
            pattern: ^/(docs.*|index\.(json|jsonld|html))
            security: false

        api:
            pattern: .*
            security: true
            provider: keycloak_bearer_user_provider
            custom_authenticators:
                - keycloak_bearer_authenticator
            stateless: true
